QA-2580 Playwright POC Tests
pagarme/magento2 pull request #153
Opened 2023-03-13 11:37 UTC by ramsessacol

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/QA-2580
| **What?**         |Esse PR tem o objetivo de inserir alguns testes automatizados para o projeto, visando fluxos E2E.
| **Why?**          | É importante para a manutenção e crescimento do projeto
| **How?**          | Inicia 

#### :package: Attachments (if appropriate)
![magento_allure_report_02](https://user-images.githubusercontent.com/89397089/224691209-61ff2f6b-72c2-474a-8739-6f4e1371557b.png)

#### :speech_balloon: Important guidelines

* Add pull request labels.
* Check base branch.
* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!

2023-03-13 17:46 UTC, paulofachini commented on e2e/Dockerfile
> +RUN npx npx playwright install --with-deps
aqui ficou o comando "npx" duplicado.

2023-03-13 17:46 UTC, paulofachini commented on e2e/Dockerfile
> +CMD [ "npx", "playwright", "test"]
o github está sugerindo incluir uma linha em branco no final do arquivo, agradeço se puder verificar todos os aquivos desse PR.

2023-03-13 17:46 UTC, paulofachini commented on e2e/helper/checkout_helper.js
> +
por gentileza remover a linha em branco que está a mais.

2023-03-13 17:46 UTC, paulofachini commented on e2e/helper/data_helper.js
> +
por gentileza remover a linha em branco que está a mais.

2023-03-13 17:46 UTC, paulofachini commented on e2e/helper/pagarme_helper.js
> +
por gentileza remover a linha em branco que está a mais.

2023-03-13 17:46 UTC, paulofachini commented on e2e/helper/checkout_helper.js
> +
por gentileza remover a linha em branco que está a mais.

2023-03-13 17:46 UTC, paulofachini commented on e2e/helper/checkout_helper.js
> +    await page.waitForTimeout(1000); //ninguem gosta disso, imagina ter que usar ne?
Uma dúvida, talvez posso estar chovendo no molhado. 
Mas não conseguimos fazer esperar por algum elemento ou situação ocorrer, ao invés de usar waitForTimeout?

2023-03-13 17:55 UTC, ramsessacol commented on e2e/helper/checkout_helper.js
> +    await page.waitForTimeout(1000); //ninguem gosta disso, imagina ter que usar ne?
Essa é a parte `delicada` da interação de alguns elementos, as vezes eles já estão com visibilidade, mas não com `disponibilidade` para interagir. Nesse caso, até achar uma solução mais sensata, optei por jogar o nosso famosos `sleep` . Não está afetando o script e é bem curto... Futuramente vai ser ajustado.

2023-03-13 18:03 UTC, paulofachini commented on e2e/helper/checkout_helper.js
> +    await page.waitForTimeout(1000); //ninguem gosta disso, imagina ter que usar ne?
Entendi, obrigado Ramses.

2023-03-13 18:09 UTC, paulofachini approved these changes

2023-03-13 18:10 UTC, gabriellealvim commented on e2e/helper/checkout_helper.js
> +    await page.waitForTimeout(1000); //ninguem gosta disso, imagina ter que usar ne?
Uma dúvida, você chegou a tentar o waitForSelector Ramses? Como você disse realmente acaab não impactando, mas talvez seja uma alternativa, na real não sei kkkk, pq não sei ao certo do que se trata o elemento, mas normalmente quando se trata de disponibilidade de elementos utilizo e funciona :)

2023-03-13 18:16 UTC, ramsessacol commented on e2e/helper/checkout_helper.js
> +    await page.waitForTimeout(1000); //ninguem gosta disso, imagina ter que usar ne?
@gabriellealvim , sim e cada 10 execuções, 6 ele tava lá, mas não apto para interagir... =(

2023-03-13 18:18 UTC, gabriellealvim commented on e2e/helper/data_helper.js
> +        credit_card_number: '4000000000000010',
Uma dúvida de leiga, tem algum problema esses dados estarem inseridos sem process.env? Por se tratar de um repositório "public" daria algum BO se conseguissem acessar os dados?

2023-03-13 18:20 UTC, gabriellealvim commented on e2e/helper/pagarme_helper.js
> +}
Aqui está reclamando de uma linha faltando, não sei se seri o caso de colocar

2023-03-13 18:27 UTC, gabriellealvim commented on e2e/tests/cartao-de-credito.e2e.test.js
> +        const user = user_information();
Não sei se faz sentido pq é algo bem bobô, mas talvez faça não ter a const e as ações do waits alinhas, mas isso é só pq eu tenho toque e talvez nem faça sentido, entra como dúvida

2023-03-13 18:29 UTC, gabriellealvim commented on e2e/helper/checkout_helper.js
> +    await page.waitForTimeout(1000); //ninguem gosta disso, imagina ter que usar ne?
Eitaaa entendi, que BO. Obrigada por responder Ramses, nesse caso vida que segue kkk

2023-03-13 18:41 UTC, ramsessacol commented on e2e/helper/data_helper.js
> +        credit_card_number: '4000000000000010',
Tecnicamente é o mesmo dado que passamos, em documentação, quando testamos . Por isso não achei tão critico para tirar em um .env

2023-03-13 18:41 UTC, ramsessacol commented on e2e/tests/cartao-de-credito.e2e.test.js
> +        const user = user_information();
Ham.... é... então, não entendi...  =)

2023-03-13 18:49 UTC, gabriellealvim commented on e2e/helper/data_helper.js
> +        credit_card_number: '4000000000000010',
Aaah então está tranquilo

2023-03-14 12:52 UTC, alinecb approved these changes

2023-03-14 16:46 UTC, gabriellealvim commented on e2e/tests/cartao-de-credito.e2e.test.js
> +        const user = user_information();
Hahah, só ignora agora que entendi :)

2023-03-14 16:46 UTC, gabriellealvim approved these changes

2023-03-16 10:55 UTC, dayaneCsantos commented on e2e/.gitignore
> +.DS_Store
Reclamando de uma linha ao final aqui

2023-03-16 10:55 UTC, dayaneCsantos commented on e2e/helper/checkout_helper.js
> +}
reclamando de uma linha ao final

2023-03-16 10:55 UTC, dayaneCsantos commented on e2e/helper/data_helper.js
> +const address_infomration = () => {
address_information acredito eu...

2023-03-16 10:55 UTC, dayaneCsantos commented on e2e/helper/data_helper.js
> +        fisrt_address_line: faker.address.street(),
acho que seria first

2023-03-16 10:55 UTC, dayaneCsantos commented on e2e/helper/data_helper.js
> +}
Reclamando de uma linha ao final

2023-03-16 10:55 UTC, dayaneCsantos commented on e2e/helper/product_helper.js
> +}
Reclamando de uma linha ao final

2023-03-16 10:55 UTC, dayaneCsantos commented on e2e/package.json
> +  }
Reclamando de uma linha aqui

2023-03-16 10:55 UTC, dayaneCsantos commented on e2e/playwright.config.js
> +}
reclamando de uma linha aqui

2023-03-16 10:55 UTC, dayaneCsantos commented on e2e/tests/cartao-de-credito.e2e.test.js
> +})
reclamando de uma linha aqui

2023-03-16 11:29 UTC, ramsessacol commented on e2e/.gitignore
> +.DS_Store
Mas é um .gitignore... 😕

2023-03-16 12:15 UTC, paulofachini approved these changes

2023-03-16 13:23 UTC, gabriellealvim approved these changes

2023-03-17 21:15 UTC, vannessasoares submitted a review, later dismissed

2023-03-20 16:43 UTC, dayaneCsantos submitted a review, later dismissed

2023-03-21 12:50 UTC, gabriellealvim approved these changes

2023-03-21 14:00 UTC, marinavianapagarme submitted a review, later dismissed

2023-03-22 19:48 UTC, fabiano-mallmann requested changes

2023-03-22 19:48 UTC, fabiano-mallmann commented on e2e/helper/product_helper.js
> +    await page.click('#product-item-info_1')
Por conta do Magento gerar um id dinâmico de acordo com o product_id, essa regra atual funcionará apenas caso o product_id for igual a 1. Creio que para o fluxo funcionar melhor deveria buscar pelo primeiro item da lista:
`await page.click('.product-item-info')`

2023-03-24 20:01 UTC, acedraz approved these changes

2023-03-28 17:09 UTC, merged