Implements hub integration
pagarme/magento2 pull request #20
Opened 2021-05-20 19:56 UTC by netorodrigues

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-125
| **What?**         | Adds hub integration
| **Why?**          | To make the module configuration process easier

**Important Notes:**

- The integration is made with **staging hub**, we still need to change it to production later
- After we change this integration to **production hub**, we also need to remove this if: https://github.com/pagarme/magento2/blob/feature/PAOP-111-implements-hub-integrations/view/frontend/web/js/core/checkout/CreditCardToken.js#L27
  - It was necessary because the public key is generated in staging after integration, so we need to use it to use it as a paramenter to create a card token also in staging API.
- This PR also paints the Hub Button with Pagar.me brand and color, as the image below:
![](https://i.imgur.com/8vEmPdU.png)

#### :package: Attachments (if appropriate)
Add additional informations like screenshots, issue link, etc

#### :speech_balloon: Important guidelines

* Add pull request labels.
* Check base branch.
* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!

2021-05-21 14:01 UTC, vberardi approved these changes
Coloquei apenas algumas sugestões.

2021-05-21 14:14 UTC, netorodrigues commented on Controller/Adminhtml/Hub/Index.php
> +            $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/Pagarme_Hub.log');
Eu removi esse trecho com esse writter, achei que a ideia seria fazer todos os logs dentro do core nesse fluxo aqui: https://github.com/pagarme/ecommerce-module-core/blob/master/src/Hub/Services/HubIntegrationService.php#L48

Porque aí a gente teria logs unificado pros vários módulos, mas nesse fluxo eu também não achei chamadas ao logservice... Talvez seja um ponto de melhoria a se anotar no backlog

2021-05-21 14:17 UTC, netorodrigues commented on etc/adminhtml/system/global.xml
> -        <field id="test_mode" showInDefault="1" showInStore="1" showInWebsite="1" sortOrder="20" translate="label" type="select">
Ele só vai deixar de atualizar esses campos que a gente removeu a cada save das configurações, mas mantém os ultimos valores salvos. O uso desses valores ainda funciona porque a gente vai diretamente no banco pegar eles quando montamos o objeto de configurações, aqui: https://github.com/pagarme/magento2/blob/56271aac73ad2e831b67e148775c471097d7f914/Concrete/Magento2CoreSetup.php#L324

2021-05-21 14:30 UTC, netorodrigues commented on view/adminhtml/web/css/hub_button.css
> +}
Feito!

2021-05-21 14:30 UTC, netorodrigues commented on view/adminhtml/web/js/hubIntegration.js
> +        this.mundipaggLogo = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAYAAAByDd+UAAAT3XpUWHRSYXcgcHJvZmlsZSB0eXBlIGV4aWYAAHjarZppdty4FYX/YxVZAuZhORjPyQ6y/HwXLMmyJNvdSVt2scRigcAb7gDa7P/
Feito!

2021-05-21 16:22 UTC, willian-soaresferreira approved these changes

2021-05-21 16:22 UTC, willian-soaresferreira commented on Setup/InstallSchema.php
> +                ->setComment('Customer Table')
`->setComment('Hub Install Token Table')`

2021-05-21 16:22 UTC, willian-soaresferreira commented on view/adminhtml/layout/adminhtml_system_config_edit.xml
> +		<css src="Pagarme_Pagarme::css/hub_button.css" />
aparentemente ficou com um TAB a mais.

2021-05-21 16:23 UTC, willian-soaresferreira requested changes
Muito bom ver o Hub saindo mano, show de bola! :)
Deixei umas sugestões e qualquer dúvida só avisar.

2021-05-21 19:11 UTC, netorodrigues commented on Gateway/Transaction/Base/Config/Config.php
> +    public function isHubEnabled()
Inicialmente eu tentei usar esse método também, mas percebi que são dois arquivos de configuração diferentes. Esse que eu mexi parece ser um conjunto de configurações que é enviada para o JS do checkout, já o `Kernel/Aggregates/Configuration.php` é um arquivo de configurações do próprio módulo em si. Eu não vi problema em replicar o `isHubEnabled` aí porque essa classe mesmo já tem alguns métodos que lêem dados diretamente do Magento2 (`getPublicKey`, `getSectetKey`...) sem fazer uso dos métodos presentes no `Kernel/Aggregates/Configuration.php` pra obter esses dados

2021-05-21 19:17 UTC, netorodrigues commented on Controller/Adminhtml/Hub/Index.php
> +        );
É que estamos lendo esse campo para preencher a variável `hubInstallId` das configurações do core, que faz com que esse método funcione: https://github.com/pagarme/ecommerce-module-core/blob/master/src/Kernel/Aggregates/Configuration.php#L300

No projeto do magento 2 a gente tem as tabelas do próprio magento (`core_config_data`) e a do ecommerce-module-core (`pagarme_module_core_configuration`). E existem fluxos que montam o objeto de configuração baseado na tabela do magento e salvam na do ecommerce-module-core. Se a gente não salva esse valor do lado do magento, acontece algumas vezes dos valores da tabela `pagarme_module_core_configuration` serem sobrescritos. Não sei dizer se isso também acontecia no Magento 1, mas é por isso que eu preciso salvar esse valor do install_id aí nessa linha.

2021-05-21 19:20 UTC, netorodrigues commented on Controller/Adminhtml/Hub/Index.php
> +                $params['&install_token'],
Não funciona. Eu até tentei montar a redirect url de forma que o Hub me devolvesse esse parâmetro sem o `&`, mas não consegui. Acabei deixando assim também por ser algo que está presente na integração lá no Magento 1, então achei que fosse um problema conhecido ou fosse a forma esperada de se fazer o redirecionamento mesmo.

https://github.com/mundipagg/magento/blob/master/app/code/community/Mundipagg/Paymentmodule/controllers/HubController.php#L41

2021-05-21 19:22 UTC, netorodrigues commented on view/adminhtml/layout/adminhtml_system_config_edit.xml
> +		<css src="Pagarme_Pagarme::css/hub_button.css" />
Resolvido

2021-05-21 19:22 UTC, netorodrigues commented on Setup/InstallSchema.php
> +                ->setComment('Customer Table')
Resolvido

2021-05-21 19:23 UTC, netorodrigues commented on Block/Adminhtml/Form/Field/HubIntegration.php
> +    private function getBaseViewUrl($installId)
Modificado

2021-05-21 19:41 UTC, netorodrigues commented on Block/Adminhtml/Form/Field/HubIntegration.php
> +        new-window="%s"></p>', $hubUrl, $buttonText, $newWindow);
Modificado

2021-05-21 19:41 UTC, netorodrigues commented on Block/Adminhtml/Form/Field/HubIntegration.php
> +        return $installId ? $this->getBaseViewUrl($installId->getValue()) : $this->getBaseIntegrateUrl();
Modificado.

2021-05-21 19:41 UTC, netorodrigues commented on Block/Adminhtml/Form/Field/HubIntegration.php
> +        return "https://stghub.mundipagg.com/apps/{$this->getPublicAppKey()}/authorize?redirect={$this->getRedirectUrl()}&install_token/{$this->getInstallToken()}";
Modificado.

2021-05-21 19:43 UTC, netorodrigues commented on Block/Adminhtml/Form/Field/HubIntegration.php
> +        return "https://stghub.mundipagg.com/apps/{$this->getPublicAppKey()}/edit/{$installId}";
Modificado

2021-05-21 20:28 UTC, vberardi approved these changes

2021-05-21 23:30 UTC, willian-soaresferreira approved these changes

2021-05-24 13:14 UTC, merged

2021-05-31 20:23 UTC, netorodrigues commented
We needed to recreate this PR in order to get the correct changes in develop branch because of a rebase issue there, so we made it in #22.