Moves upgrade data and schema to install data and schema
pagarme/magento2 pull request #21
Opened 2021-05-27 15:28 UTC by netorodrigues

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**           | https://mundipagg.atlassian.net/browse/PAOP-90
| **What?**         | Removes old mundipagg's databases changes based on versoning.
| **Why?**          | To start a new versioning way in pagarme's module.
| **How?**          | Moving all script changes made in upgrade scripts (data and schema) to install scripts (data and schema)

**Important Notes**
- this PR also removes methods that apply changes to tables that do not appear to be in use today by the module. These methods are all listed in **Recurrence.php** and **UpgradeData.php** files changed in this PR.
- This PR also solves a bug in magento's admin configuration page, datailed in https://mundipagg.atlassian.net/browse/PAOP-150 

#### :package: Attachments (if appropriate)

#### :speech_balloon: Important guidelines

* Add pull request labels.
* Check base branch.
* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!

2021-05-27 15:34 UTC, vberardi submitted a review, later dismissed

2021-05-28 21:09 UTC, willian-soaresferreira requested changes
Boa! Só deixei 2 detalhes mesmo como sugestão.

2021-05-31 12:31 UTC, netorodrigues commented on Setup/InstallData.php
> +        \Magento\Customer\Setup\CustomerSetupFactory $customerSetupFactory
Fica melhor mesmo. Modificado!

2021-05-31 12:31 UTC, netorodrigues commented on Setup/InstallData.php
> +        $this->addsCustomerIdPagarme($setup);
Feito

2021-05-31 20:09 UTC, closed without merging

2021-05-31 20:21 UTC, netorodrigues commented
This PR was closed due to a rebase issue in develop branch. We needed to recreate it in order to get the correct changes, so we made it in #23