fix: brand validation call
pagarme/magento2 pull request #245
Opened 2023-09-12 19:48 UTC by fabiano-mallmann

2023-09-12 19:54 UTC, mateus-picoloto requested changes

2023-09-12 19:54 UTC, mateus-picoloto commented on view/frontend/web/js/core/checkout/Bin.js
> +            this.checkedBins[this.binValue] = data.status != 404 ? data.brand : '';
Poderia ser uma comparação de igualdade estrita

2023-09-12 19:54 UTC, mateus-picoloto commented on view/frontend/web/js/core/checkout/Bin.js
> +            this.selectedBrand = data.status != 404 ? data.brand : '';
Poderia ser uma comparação de igualdade estrita

2023-09-12 19:57 UTC, fabiano-mallmann commented on view/frontend/web/js/core/checkout/Bin.js
> +            this.checkedBins[this.binValue] = data.status != 404 ? data.brand : '';
Feito

2023-09-12 19:57 UTC, fabiano-mallmann commented on view/frontend/web/js/core/checkout/Bin.js
> +            this.selectedBrand = data.status != 404 ? data.brand : '';
Feito

2023-09-12 20:01 UTC, mateus-picoloto approved these changes

2023-09-13 16:42 UTC, RafaMelazzo approved these changes

2023-09-15 17:35 UTC, merged