feat: dash validation
pagarme/magento2 pull request #268
Opened 2023-10-26 15:24 UTC by mateus-picoloto

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-329
| **What?**         | Account config validation.
| **Why?**          | Validate store config with account config.
| **How?**          | Account config validation.

2023-10-27 19:34 UTC, fabiano-mallmann commented on view/adminhtml/web/css/integration_buttons.css
> +#hub-button, #dash-button {
@RafaMelazzo coloca um nome menos genérico, preferencialmente pagarme-hub-button

2023-10-27 19:35 UTC, fabiano-mallmann commented on etc/events.xml
> +        <observer name="" instance="Pagarme\Pagarme\Observer\DashConfigValidatorObserver"/>
Acho valido adicionar um nome

2023-10-27 20:08 UTC, mateus-picoloto commented on etc/events.xml
> +        <observer name="" instance="Pagarme\Pagarme\Observer\DashConfigValidatorObserver"/>
Ajustado

2023-10-31 15:02 UTC, RafaMelazzo commented on view/adminhtml/web/css/integration_buttons.css
> +#hub-button, #dash-button {
Corrigido

2023-10-31 19:56 UTC, RafaMelazzo requested changes

2023-10-31 19:56 UTC, RafaMelazzo commented on etc/adminhtml/system/transaction/creditcard.xml
> +            <comment><![CDATA[<p id='creditcard_soft_description_comment'>Max size: 13.</p>]]></comment>
Voltar com essa estrutura e adicionar a algum elemento pai das configurações uma classe indicando o contrato do cliente (`pagarme_psp` ou `pagarme_gateway`), para voltarmos com esse recurso via script.

2023-10-31 19:56 UTC, RafaMelazzo commented on etc/adminhtml/system/transaction/debit.xml
> +            <comment><![CDATA[<p id='debit_soft_description_comment'>Max size: 13.</p>]]></comment>
Idem ao comentário do arquivo `etc/adminhtml/system/transaction/creditcard.xml`

2023-10-31 19:56 UTC, RafaMelazzo commented on etc/adminhtml/system/transaction/voucher.xml
> +            <comment><![CDATA[<p id='voucher_soft_description_comment'>Max size: 13.</p>]]></comment>
Idem ao comentário do arquivo `etc/adminhtml/system/transaction/creditcard.xml`

2023-10-31 19:56 UTC, RafaMelazzo commented on view/adminhtml/web/js/integrationType.js
Retornar com as funções do soft descriptor, ajustando a identificação dos elementos com base nas classes sugeridas no comentário do arquivo `etc/adminhtml/system/transaction/creditcard.xml`

2023-11-01 17:46 UTC, mateus-picoloto commented on etc/adminhtml/system/transaction/creditcard.xml
> +            <comment><![CDATA[<p id='creditcard_soft_description_comment'>Max size: 13.</p>]]></comment>
Ajustado

2023-11-01 17:46 UTC, mateus-picoloto commented on etc/adminhtml/system/transaction/voucher.xml
> +            <comment><![CDATA[<p id='voucher_soft_description_comment'>Max size: 13.</p>]]></comment>
Ajustado

2023-11-01 17:46 UTC, mateus-picoloto commented on etc/adminhtml/system/transaction/debit.xml
> +            <comment><![CDATA[<p id='debit_soft_description_comment'>Max size: 13.</p>]]></comment>
Ajustado

2023-11-01 17:46 UTC, mateus-picoloto commented on view/adminhtml/web/js/integrationType.js
Ajustado

2023-11-01 19:16 UTC, RafaMelazzo approved these changes

2023-11-01 19:49 UTC, fabiano-mallmann approved these changes

2023-11-01 19:51 UTC, merged