Implements multi-store Hub integration
pagarme/magento2 pull request #27
Opened 2021-06-11 12:27 UTC by vberardi

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-145
| **What?**         | Implements multi-store Hub integration
| **Why?**          | To allow easy integration on Hub Pagarme
| **How?**          | Adding "website" parameter in hub integrations

2021-06-14 22:56 UTC, willian-soaresferreira approved these changes

2021-06-14 22:56 UTC, willian-soaresferreira commented on view/frontend/web/js/core/checkout/CreditCardToken.js
>  CreditCardToken.prototype.getToken = function (pkKey, isHubEnabled) {
Precisa matar o uso desse parâmetro `isHubEnabled`, nesse e nos demais arquivos que também utilizaram ele pra trocar a url para `stgapi`, nesse PR https://github.com/pagarme/magento2/pull/22/files. Qualquer dúvida é só falar com o @netorodrigues.  Tudo bem não ser nesse PR, mas nessa sprint é o ideal, talvez na tarefa de "remover configs e sujeiras".

2021-06-15 14:17 UTC, willian-soaresferreira commented
@vberardi uma coisa que pensei mas esqueci de comentar ontem, é importante seguir o uso dos gitmojis e não deixar commit sem um gitmoji, pois facilita em futuras buscas pelos commits, encontrando mais facilmente o que foi bugfix, feature, etc :)

2021-06-15 14:26 UTC, netorodrigues requested changes

2021-06-15 14:26 UTC, netorodrigues commented on Block/Adminhtml/Form/Field/HubIntegration.php
> +        return $this->_storeManager->getStore($store)->getWebsiteId();
A gente não poderia usar esse método aqui pra pegar a store? https://github.com/pagarme/magento2/blob/master/Concrete/Magento2CoreSetup.php#L498

2021-06-15 14:26 UTC, netorodrigues commented on Controller/Adminhtml/Hub/Index.php
> +                    $this->getCallbackUrl() . '?websiteId=' . $websiteId,
Não seria melhor o `getCallbackUrl()` retornar a url toda, com o trecho do `'?websiteId=' . $websiteId` ?

2021-06-15 19:46 UTC, vberardi commented on view/frontend/web/js/core/checkout/CreditCardToken.js
>  CreditCardToken.prototype.getToken = function (pkKey, isHubEnabled) {
Ajustado!

2021-06-15 19:46 UTC, vberardi commented on Block/Adminhtml/Form/Field/HubIntegration.php
> +        return $this->_storeManager->getStore($store)->getWebsiteId();
Ajustado!

2021-06-15 19:46 UTC, vberardi commented on Controller/Adminhtml/Hub/Index.php
> +                    $this->getCallbackUrl() . '?websiteId=' . $websiteId,
Ajustado!

2021-06-15 20:09 UTC, willian-soaresferreira approved these changes

2021-06-15 20:26 UTC, netorodrigues approved these changes

2021-06-15 21:01 UTC, merged