creating 3ds object
pagarme/magento2 pull request #280
Opened 2023-12-01 15:22 UTC by RafaMelazzo

2023-12-01 16:32 UTC, mateus-picoloto requested changes

2023-12-01 16:32 UTC, mateus-picoloto commented on view/frontend/web/js/core/checkout/TdsToken.js
> +    quote
Indentação aqui não está seguindo o padrão do arquivo

2023-12-01 16:32 UTC, mateus-picoloto commented on view/frontend/web/js/core/models/CreditCardModel.js
> +                    // _self.placeOrderObject.placeOrder();
Tirar o comentário do código

2023-12-01 18:05 UTC, mateus-picoloto approved these changes

2023-12-04 18:11 UTC, fabiano-mallmann approved these changes

2023-12-04 19:53 UTC, merged