feat: add loading after PlaceOrder click and fix Tds call
pagarme/magento2 pull request #283
Opened 2023-12-12 13:03 UTC by fabiano-mallmann

2023-12-12 13:04 UTC, fabiano-mallmann commented
@mateus-picoloto @RafaMelazzo Tem uns comentários ali, mas é para poder ativar/desativar o módulo por conta do "Gateway Only"

2023-12-12 21:19 UTC, mateus-picoloto requested changes

2023-12-12 21:19 UTC, mateus-picoloto commented on view/frontend/templates/payment/tds.phtml
> +    .challengeIframeElement {
O css não poderia ficar em um arquivo separado?

2023-12-12 21:19 UTC, mateus-picoloto commented on view/frontend/templates/payment/tds.phtml
> +        style="width: 500px; height: 600px"
O css não poderia ficar em um arquivo separado?

2023-12-12 21:19 UTC, mateus-picoloto commented on view/frontend/web/js/core/checkout/Tds.js
> +		constructor(formObject){
A formação dessas primeiras funções está diferente das demais desse arquivo

2023-12-13 14:41 UTC, RafaMelazzo approved these changes

2023-12-13 17:44 UTC, RafaMelazzo approved these changes

2023-12-13 17:44 UTC, mateus-picoloto approved these changes

2023-12-13 17:46 UTC, merged