feat: alternate pix and billet info
pagarme/magento2 pull request #307
Opened 2024-02-05 21:03 UTC by RafaMelazzo

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **stg**.

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [ ] Refatoração
- [x] Adição de funcionalidade
- [ ] Correção de bug
- [ ] Otimização
- [ ] Atualização de documentação

### Descrição
Adicionado método alternativo para buscar as informações de QrCode de Pix ou URL de Boleto. Ver tarefa: https://mundipagg.atlassian.net/browse/PAOPN-663

### Cenários testados
Defini `null` no `$orderId` para testar o retorno da nova função quando a original falhar. Retorno está conforme esperado. Testado pedidos com Pix, Boleto e Cartão de Crédito. Todos ok!

2024-02-05 21:10 UTC, mateus-picoloto requested changes

2024-02-05 21:10 UTC, mateus-picoloto commented on Gateway/Transaction/Base/Command/InitializeCommand.php
> +                if (!is_null($pagarmeOrder->getPixOrBilletTransaction())) {
Poderia salvar o resultado da chamada do $pagarmeOrder->getPixOrBilletTransaction() em uma variável para não chamar 2 vezes o mesmo método

2024-02-05 21:10 UTC, mateus-picoloto commented on Helper/Payment/Billet.php
> -            if (!$orderId) {
Esse if não deveria continuar existindo abaixo do novo if adicionado?

2024-02-06 12:10 UTC, mateus-picoloto approved these changes

2024-02-06 12:26 UTC, mauriciohaygert approved these changes

2024-02-07 13:29 UTC, merged