feat: save recipient with inicial status
pagarme/magento2 pull request #328
Opened 2024-04-22 18:02 UTC by RafaMelazzo

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **develop**.

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [ ] Refatoração
- [x] Adição de funcionalidade
- [ ] Correção de bug
- [ ] Otimização
- [ ] Atualização de documentação

### Descrição
* Novos recebedores salvos com o status `registered`
* Recebedores existentes salvos na plataforma com o status recebido do Pagar.me
### Cenários testados
- Status salvo no banco de dados
- Sem teste com status do KYC Details ainda

2024-04-30 19:22 UTC, mateus-picoloto requested changes

2024-04-30 19:22 UTC, mateus-picoloto commented on Model/Api/Recipient.php
> +            if (!empty($params['status']) && !empty($params['kyc_status'])) {
O $params['kyc_status'] não está sendo mandado mais, então acho que daria pra remover ele do if

2024-04-30 19:22 UTC, mateus-picoloto commented on Model/Api/Recipient.php
> +        if (empty($params['status'])) {
Esse if precisa ainda? Que já está sendo colocado o status de cadastrado [aqui](https://github.com/pagarme/magento2/pull/328/files#diff-ae535d0b781dbce425a14a04caebf76b73da23f1d709b429974e2c8687f3d96cR84).

2024-04-30 19:22 UTC, mateus-picoloto commented on etc/db_schema.xml
> +        <column name="status" xsi:type="varchar" length="255" nullable="false" comment="Recipient withdrawal status on Pagar.me"/>
Ele é nullable igual a true, por causa dos recebedores antigos.

2024-04-30 20:45 UTC, mateus-picoloto approved these changes

2024-05-03 19:51 UTC, fabiano-mallmann approved these changes

2024-05-03 20:04 UTC, merged