feat: added recipient status and recipient link to recipient list page
pagarme/magento2 pull request #333
Opened 2024-04-29 14:41 UTC by mateus-picoloto

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [ ] Refatoração
- [x] Adição de funcionalidade
- [ ] Correção de bug
- [ ] Otimização
- [ ] Atualização de documentação

### Descrição
Adição da coluna de status de recebedor na listagem de recebedor do admin, além da api de geração do link de kyc sendo chamada para exibir em uma modal.

### Cenários testados
Teste de webhooks com os status do [épico](https://mundipagg.atlassian.net/browse/PA-933).

2024-04-30 14:59 UTC, RafaMelazzo requested changes

2024-04-30 14:59 UTC, RafaMelazzo commented on view/adminhtml/web/css/pagarme_style.css
> +}
Poderia ter um estilo com todas as propriedades comuns. Exemplo:

```
.data-grid td .kyc-validation {
    background: #000 none repeat scroll 0 0;
    border: 1px solid #000;
    display: block;
    font-weight: bold;
    line-height: 17px;
    padding: 0 3px;
    text-align: center;
}
```

Depois cada estilo personalizando apenas as cores:

```
.data-grid td .recipient-status-waiting_for_analysis {
    background-color: #fff7d6;
    border-color: #974f0c;
    color: #974f0c;
}
```

2024-04-30 14:59 UTC, RafaMelazzo commented on view/adminhtml/web/js/grid/columns/recipientStatus.js
> +    'mage/translate',
Pode remover este se não funcionou...

2024-04-30 14:59 UTC, RafaMelazzo commented on view/adminhtml/web/js/grid/columns/recipientStatus.js
> +], function (_, Column, mageUrl, alert, $, $t) {
Remover o `$t` também.

2024-04-30 14:59 UTC, RafaMelazzo commented on i18n/pt_BR.csv
> +"Recipient not founded.","Recebedor não encontrado."
Esses status estão sendo utilizados?

2024-04-30 14:59 UTC, RafaMelazzo commented on view/adminhtml/web/js/grid/columns/recipientStatus.js
> +            // Using portuguese string because mage/translate and knockout i18n were not working
Eu sei que você me perguntou sobre isso e eu achei uma boa ideia na hora, hahaha... Mas estava pensando, será que não seria melhor um `@todo` no lugar do comentário, pra ajudar a encontrar esses caras quando formos corrigir no futuro?

2024-04-30 15:19 UTC, mateus-picoloto commented on i18n/pt_BR.csv
> +"Recipient not founded.","Recebedor não encontrado."
Serão utilizado na demanda de editar o status, então acredito que da para deixar.

2024-04-30 15:20 UTC, mateus-picoloto commented on view/adminhtml/web/js/grid/columns/recipientStatus.js
> +], function (_, Column, mageUrl, alert, $, $t) {
Está sendo usado aqui: https://github.com/pagarme/magento2/pull/333/files#diff-53daba0944e865666872a159c787dde428aecdec6c8f59873e20bc9160943114R75

2024-04-30 19:49 UTC, mateus-picoloto commented on view/adminhtml/web/css/pagarme_style.css
> +}
Ajustado.

2024-04-30 19:49 UTC, mateus-picoloto commented on view/adminhtml/web/js/grid/columns/recipientStatus.js
> +            // Using portuguese string because mage/translate and knockout i18n were not working
Ajustado.

2024-04-30 20:00 UTC, RafaMelazzo approved these changes

2024-05-03 19:59 UTC, fabiano-mallmann requested changes

2024-05-03 19:59 UTC, fabiano-mallmann commented on view/adminhtml/web/js/grid/columns/recipientStatus.js
> +], function (_, Column, mageUrl, alert, $, $t) {
Poderia alterar o nome dessa variável, tornar ela um pouco mais legível

2024-05-03 19:59 UTC, fabiano-mallmann commented on view/adminhtml/web/js/grid/columns/recipientStatus.js
> +            } catch (e) {
Tornar variável mais legível

2024-05-03 20:02 UTC, mateus-picoloto commented on view/adminhtml/web/js/grid/columns/recipientStatus.js
> +            } catch (e) {
Ajustado

2024-05-03 20:04 UTC, fabiano-mallmann approved these changes

2024-05-03 21:25 UTC, RafaMelazzo approved these changes

2024-05-06 12:37 UTC, merged