feat: added update status to recipient edit/view page
pagarme/magento2 pull request #334
Opened 2024-05-03 19:16 UTC by mateus-picoloto

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [ ] Refatoração
- [x] Adição de funcionalidade
- [ ] Correção de bug
- [ ] Otimização
- [ ] Atualização de documentação

### Descrição
Adição da funcionalidade de atualizar o status do recebedor ao acessar a página de visualização do recebedor caso não possua status salvo.

### Cenários testados
Testado com recebedor antigo e seu status é atualizado.
Testado com recebedor já com o status salvo e o status não é atualizado.

2024-05-03 20:11 UTC, fabiano-mallmann approved these changes

2024-05-03 20:13 UTC, fabiano-mallmann commented
O teste está falhando na pipe porque não tem a classe que o @mateus-picoloto criou da SDK ainda.

2024-05-03 21:22 UTC, RafaMelazzo requested changes

2024-05-03 21:22 UTC, RafaMelazzo commented on Model/Api/Recipient.php
> +                . "<b>withdrawal permission status</b>. He can only withdraw his sales amounts once the status is "
Alterar `withdrawal permission status` para apenas `status`, conforme solicitação da PM

2024-05-03 21:22 UTC, RafaMelazzo commented on i18n/pt_BR.csv
> +"<p>He can now sell, but remember to check his <b>withdrawal permission status</b>. He can only withdraw his sales amounts once the status is <i>“active”</i></p>","<p>Ele já consegue vender, mas lemb
Alterar `withdrawal permission status` para apenas `status`, conforme solicitação da PM

2024-05-03 21:22 UTC, RafaMelazzo commented on i18n/pt_BR.csv
> +"<p>He can now sell, but it is necessary to complete the security validation so that he can withdraw the sales amounts in the future.</p><p><span class='pagarme-alert-text'>Attention!</span> Keep up
Alterar `withdrawal permission status` para apenas `status`, conforme solicitação da PM

2024-05-06 12:24 UTC, mateus-picoloto commented on Model/Api/Recipient.php
> +                . "<b>withdrawal permission status</b>. He can only withdraw his sales amounts once the status is "
Ajustado

2024-05-06 12:36 UTC, mateus-picoloto commented on i18n/pt_BR.csv
> +"<p>He can now sell, but remember to check his <b>withdrawal permission status</b>. He can only withdraw his sales amounts once the status is <i>“active”</i></p>","<p>Ele já consegue vender, mas lemb
Ajustado

2024-05-06 12:36 UTC, mateus-picoloto commented on i18n/pt_BR.csv
> +"<p>He can now sell, but it is necessary to complete the security validation so that he can withdraw the sales amounts in the future.</p><p><span class='pagarme-alert-text'>Attention!</span> Keep up
Ajustado

2024-05-06 13:31 UTC, RafaMelazzo approved these changes

2024-05-06 13:32 UTC, merged