Paopn 708/feat add kyc validation to recipient dash
pagarme/magento2 pull request #335
Opened 2024-05-07 21:29 UTC by RafaMelazzo

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **develop**.

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [ ] Refatoração
- [x] Adição de funcionalidade
- [ ] Correção de bug
- [ ] Otimização
- [ ] Atualização de documentação

### Descrição
* Adicionado modal na Dashboard do recebedor para validação de segurança
* Alterado link do KYC na modal do admin para um input text com botão para cópia

### Cenários testados
* Modal funcionando na Dashboard do recebedor (não foi possível testar o QRCode, por dependência de outro time)
* Input exibido na modal do admin

2024-05-08 12:07 UTC, mateus-picoloto approved these changes

2024-05-08 12:28 UTC, mateus-picoloto approved these changes

2024-05-08 12:34 UTC, mateus-picoloto approved these changes

2024-05-10 18:06 UTC, fabiano-mallmann requested changes

2024-05-10 18:06 UTC, fabiano-mallmann commented on view/adminhtml/web/js/grid/columns/recipientStatus.js
> +                const errorContent = `<p>Algo deu errado, por favor tente novamente mais tarde.</p>`;
Vale a declaração da constante? Não seria melhor passar a informação direto a chamada?

2024-05-10 18:06 UTC, fabiano-mallmann commented on Block/Customer/Marketplace/Kyc.php
> +        return $this->collectionFactory->create()->addFieldToFilter(
Não sei se é uma boa ideia recuperar dados do banco via bloco, não seria melhor colocar a responsabilidade disso numa model?

2024-05-10 18:23 UTC, fabiano-mallmann commented on Block/Customer/Marketplace/Kyc.php
> +        return $this->collectionFactory->create()->addFieldToFilter(
Creio que de para ignorar esse ponto. Visto que o Magento mesmo utiliza no bloco.

2024-05-10 18:48 UTC, RafaMelazzo commented on i18n/pt_BR.csv
> +"Point the smartphone camera to read the QRCode.","Aponte a câmera do celular para ler o QRCode."
Feito!

2024-05-10 18:51 UTC, RafaMelazzo commented on i18n/pt_BR.csv
> +"Security validation not generated.","Validação de segurança não gerada."
Feito!

2024-05-10 19:23 UTC, RafaMelazzo commented on view/adminhtml/web/js/grid/columns/recipientStatus.js
> +                                const messageElement = $('#kyc-copy-message');
Feito fora da função.

2024-05-10 19:39 UTC, RafaMelazzo commented on view/adminhtml/web/js/grid/columns/recipientStatus.js
> +                const errorContent = `<p>Algo deu errado, por favor tente novamente mais tarde.</p>`;
Feito!

2024-05-10 19:47 UTC, fabiano-mallmann approved these changes

2024-05-10 20:27 UTC, merged