feat - google play
pagarme/magento2 pull request #339
Opened 2024-05-27 12:24 UTC by fabiano-mallmann

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **develop**.

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [x] Refatoração
- [x] Adição de funcionalidade
- [ ] Correção de bug
- [ ] Otimização
- [ ] Atualização de documentação

### Descrição
Adição do meio de pagamento GooglePay e refatoração de classes utilizadas para exibir os dados de cartão.

### Cenários testados

2024-06-03 17:40 UTC, RafaMelazzo requested changes

2024-06-03 17:40 UTC, RafaMelazzo commented on view/adminhtml/templates/info/debitCard.phtml
Não encontrei diferença entre este arquivo e `view/adminhtml/templates/info/creditCard.phtml`, não poderia ter apenas um deles?

2024-06-03 17:40 UTC, RafaMelazzo commented on view/adminhtml/templates/info/googlepay.phtml
Não encontrei diferença entre este arquivo e `view/adminhtml/templates/info/creditCard.phtml`, não poderia ter apenas um deles?

2024-06-03 17:40 UTC, RafaMelazzo commented on view/frontend/templates/info/googlepay.phtml
Este não tem muita diferença entre `view/frontend/templates/info/debitCard.phtml`. Não poderiam usar o mesmo template?

2024-06-03 17:40 UTC, RafaMelazzo commented on view/frontend/web/js/view/payment/googlepay.js
Ajustar indentação do arquivo para quatro espaços

2024-06-05 14:47 UTC, fabiano-mallmann commented on Block/Payment/Info/BaseCardInfo.php
> +        $charge->getLastTransaction()->getCardData()->getLastFourDigits()->getValue());
Ajustado

2024-06-05 14:48 UTC, fabiano-mallmann commented on Concrete/Magento2CoreSetup.php
> +                self::$instance->setApiBaseUrl();
Ajustado

2024-06-05 14:48 UTC, fabiano-mallmann commented on Gateway/Transaction/GooglePay/Create/Response/Validator.php
> +            throw new \InvalidArgumentException('Pagar.me  Response object should be provided');
Ajustado

2024-06-05 14:50 UTC, fabiano-mallmann commented on etc/adminhtml/system/transaction/googlepay.xml
> +        <field id="merchant_id" type="text" sortOrder="20" showInWebsite="1" showInStore="1" showInDefault="1" translate="label, comment">
Ajustado todos as ordens

2024-06-05 14:51 UTC, fabiano-mallmann commented on etc/adminhtml/system/transaction/googlepay.xml
> +        <field id="merchant_name" type="text" sortOrder="20" showInWebsite="1" showInStore="1" showInDefault="1" translate="label">
Ajustado

2024-06-05 14:52 UTC, fabiano-mallmann commented on etc/adminhtml/system/transaction/googlepay.xml
> +        <field id="sort_order" type="text" sortOrder="60" showInWebsite="1" showInStore="1" showInDefault="1" translate="label">
Ajustado

2024-06-05 16:36 UTC, fabiano-mallmann commented on etc/config.xml
> +				<title>Google Pay</title>
Ajustado

2024-06-05 16:36 UTC, fabiano-mallmann commented on etc/config.xml
> +			</pagarme_googlepay>
Ajustado

2024-06-06 13:14 UTC, fabiano-mallmann commented on view/adminhtml/templates/info/debitCard.phtml
Ajustado

2024-06-06 13:14 UTC, fabiano-mallmann commented on view/frontend/templates/info/googlepay.phtml
Ajustado

2024-06-06 13:29 UTC, fabiano-mallmann commented on view/frontend/web/js/view/payment/googlepay.js
Ajustado, a visualização aqui está um pouco bugada, pode conferir?

2024-06-06 13:39 UTC, RafaMelazzo commented on Api/GooglePayRequestDataProviderInterface.php
> +    public function getCustomerAddressDistrict($shipping);
Código não funcionou com alteração. Resolvido sem alteração.

2024-06-06 14:07 UTC, RafaMelazzo approved these changes

2024-06-07 13:14 UTC, RafaMelazzo requested changes

2024-06-07 13:14 UTC, RafaMelazzo commented on view/frontend/web/js/view/payment/googlepay.js
> +            self = this;
Definir como `const`

2024-06-10 13:48 UTC, fabiano-mallmann commented on view/frontend/web/js/view/payment/googlepay.js
> +            self = this;
Definido.

2024-06-10 14:02 UTC, mauriciohaygert approved these changes

2024-06-10 18:51 UTC, merged