Removes default config if all websites are integrated to hub
pagarme/magento2 pull request #39
Opened 2021-06-25 21:38 UTC by netorodrigues

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-167
| **What?**         | Removes public and secret keys (for test and production envs) only if all magento websites are integrated
| **Why?**          | To remove unused fields from database
| **How?**          |  Checking if all other websites are already integrated when finishing a website integration. In this case, we exclude the fields.

2021-06-25 21:47 UTC, yanpantoja submitted a review, later dismissed

2021-06-25 21:47 UTC, vberardi approved these changes

2021-06-25 23:26 UTC, willian-soaresferreira requested changes

2021-06-25 23:26 UTC, willian-soaresferreira commented on Controller/Adminhtml/Hub/Index.php
> +            $actualConfigurations = Magento2CoreSetup::getModuleConfiguration();
~~actualConfigurations~~ -> currentConfigurations

actual = real
current = atual

Outra dúvida que fiquei, se não me engano temos utilizado esse método estático `Magento2CoreSetup::getModuleConfiguration` recentemente em alguns pontos da integração com o Hub. Porém por ser estático, ele não traz dados por instância, então se houverem várias compras sendo processadas, ou outros processos, de outras lojas, não necessariamente serão retornadas as configurações corretas por loja, por exemplo, mesmo que tenhamos acabado de executar o método o `loadModuleConfigurationFromPlatform`. 

Não pensei esse ponto antes pra comentar, mas acho que pode ser um ponto pra pensarmos se faz sentido e se pode gerar algum problema (ou se estou viajando hehe). Se for isso mesmo talvez teremos que pensar em outras abordagens, ver como foi feito no Magento 1, etc.
@vberardi vê também o que você acha.

2021-06-25 23:26 UTC, willian-soaresferreira commented on Controller/Adminhtml/Hub/Index.php
> +            $sameWebsite = $websiteId === intval($currentWebsiteId);
acho que fica melhor $isSameWebsite, o que acha?

2021-06-28 18:05 UTC, vberardi approved these changes

2021-06-28 18:25 UTC, yanpantoja approved these changes

2021-06-28 19:24 UTC, willian-soaresferreira approved these changes

2021-06-28 20:16 UTC, merged