Settings in Admin (Split options)
pagarme/magento2 pull request #51
Opened 2021-08-06 20:49 UTC by yanpantoja

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-249
| **What?**         | Adds new marketplace fields configs in admin
| **Why?**          | To allow payment with split at marketplace mode

#### :package: Attachments 

![marketplace](https://user-images.githubusercontent.com/41760474/128569371-5df71f7b-2d63-45e7-8d12-db5c3c8bba7c.png)

2021-08-09 15:24 UTC, netorodrigues approved these changes

2021-08-09 20:30 UTC, willian-soaresferreira requested changes

2021-08-09 20:30 UTC, willian-soaresferreira commented on Concrete/Magento2CoreSetup.php
> +        stdClass $configData,
Deu algum problema para não poder seguir o padrão de passagem de parâmetro por referência utilizado nos outros métodos? Como por exemplo:
```
static private function fillWithRecurrenceConfig(&$dataObj, $storeConfig)
{
```
https://github.com/pagarme/magento2/blob/master/Concrete/Magento2CoreSetup.php#L571
https://www.php.net/manual/en/language.references.pass.php
 
Da forma que ficou aparentemente não funcionaria, pois a variável `$configData` teria o escopo dentro do método somente.

2021-08-09 20:30 UTC, willian-soaresferreira commented on i18n/pt_BR.csv
> +"Responsibility for chargebacks","Responsabilidade pelos estornos"
O termo `chargeback` pode deixar como `chargeback` mesmo, sem tradução, é assim que usamos nas nossas documentações normalmente. 

O termo `estorno` é equivalente à palavra `refund` em inglês e é um procedimento diferente de `chargeback`, onde o `estorno` é uma ação solicitada pelo lojista e o `chargeback` é solicitado pelo comprador.

2021-08-09 20:30 UTC, willian-soaresferreira commented on i18n/pt_BR.csv
> +"Sellers","Vendedores"
Sugiro confirmar com produto (qualquer coisa adiciona print na tarefa :D) se eles querem ou não traduzir o termo `Sellers`.

2021-08-09 20:33 UTC, willian-soaresferreira commented
Aproveitando que irá ver esses pontos, vale corrigir a palavra m**a**rketplace na mensagem do commit:
_adds new `merketplace` configs on admin_

2021-08-10 13:21 UTC, yanpantoja commented on Concrete/Magento2CoreSetup.php
> +        stdClass $configData,
Como alinhado via slack, tentei seguir a mesma estrutura do método fillWithPixConfig, que não utiliza a passagem de parâmetro por referência, pois esta não é uma técnica muito recomendada. Fiz os testes e funcionou normalmente.

2021-08-10 13:22 UTC, yanpantoja commented on i18n/pt_BR.csv
> +"Responsibility for chargebacks","Responsabilidade pelos estornos"
corrigido

2021-08-10 17:22 UTC, yanpantoja commented on i18n/pt_BR.csv
> +"Sellers","Vendedores"
Confirmado com produto pra permanecer como Vendedores

2021-08-10 23:38 UTC, willian-soaresferreira requested changes

2021-08-10 23:38 UTC, willian-soaresferreira commented on i18n/pt_BR.csv
> +"Responsibility for chargebacks","Responsabilidade pelo chargeback"
~~Responsabilidade pelo chargeback~~ -> Responsabilidade pelos chargebacks

2021-08-11 16:02 UTC, merged