Adds recipients page and table
pagarme/magento2 pull request #52
Opened 2021-08-11 15:49 UTC by yanpantoja

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-250
| **What?**         | Adds recipients page and table.
| **Why?**          | To list registered recipients

#### :package: Attachments (if appropriate)

![image](https://user-images.githubusercontent.com/41760474/129061379-ade1a534-53ba-4b90-84d1-bd5e839ef1b8.png)

2021-08-12 15:20 UTC, netorodrigues requested changes

2021-08-12 15:20 UTC, netorodrigues commented on Setup/UpgradeSchema.php
> +        $setup = $installSchema->installRecipients($setup);
A gente precisa colocar um if em volta dessa linha, parecido com o if de cima, pra evitar ficar consultando no banco se a tabela existe toda vez que a gente atualizar o módulo

2021-08-12 15:25 UTC, yanpantoja commented on Setup/UpgradeSchema.php
> +        $setup = $installSchema->installRecipients($setup);
Adicionado

2021-08-12 18:42 UTC, yanpantoja commented on Setup/InstallSchema.php
> +                    'format: si_xxxxxxxxxxxxxxxx'
Alterado

2021-08-13 20:54 UTC, netorodrigues approved these changes

2021-08-13 21:25 UTC, willian-soaresferreira approved these changes

2021-08-13 21:32 UTC, merged