Adds recipient registration page
pagarme/magento2 pull request #53
Opened 2021-08-17 15:49 UTC by yanpantoja

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-252
| **What?**         | Adds recipients registration page
| **Why?**          | To register new recipients in the API and Magento

#### :package: Attachments (if appropriate)

![recipiet-page](https://user-images.githubusercontent.com/41760474/129758016-480d437b-299a-4fe0-9c85-266f03117e98.png)

2021-08-20 18:55 UTC, netorodrigues requested changes

2021-08-20 18:55 UTC, netorodrigues commented on Model/Api/Recipient.php
> +            $form['holder_type'] = $form['type'];
A gente precisa de todos os ifs dessa função? Eu só notei essa linha definindo uma chave com valor diferente do que já existe no objeto form, fiquei meio confuso

2021-08-20 19:55 UTC, yanpantoja commented on Model/Api/Recipient.php
> +            $form['holder_type'] = $form['type'];
Não são necessários, removidos!

2021-08-20 20:24 UTC, netorodrigues approved these changes

2021-08-20 21:38 UTC, willian-soaresferreira requested changes

2021-08-20 21:38 UTC, willian-soaresferreira commented on view/adminhtml/templates/marketplace/recipients/create.phtml
> +                                        <input type="text" class="recipients_search" name="form[pagarme_id]" id="">
Parece que esse nome `recipients_search` precisa ser revisto, já que todos os campos estão utilizando essa classe e eles nem são campos de _search_.

2021-08-20 21:38 UTC, willian-soaresferreira commented on view/adminhtml/web/js/recipients.js
> +    function hiddenElementByMenuSelectValue(value, elementIdToHide)
~~hiddenElementByMenuSelectValue~~ -> **hide**ElementByMenuSelectValue
(nessa linha e também nas que chamam essa function)

2021-08-20 21:38 UTC, willian-soaresferreira commented on view/adminhtml/web/js/recipients.js
> +    function validadeDocumentSize() {
~~validadeDocumentSize~~ -> changeDocumentSizeByDocumentType
(nessa linha e também nas que chamam essa function)

Parece melhor, já que não é uma validação e sim uma troca do tamanho máximo.

2021-08-20 21:38 UTC, willian-soaresferreira commented on view/adminhtml/web/js/recipients.js
> +    function fillFieldWithSameValue()
~~fillFieldWithSameValue~~ -> fillField**s**WithSameValue 
(plural)
(nessa linha e também nas que chamam essa function)

2021-08-20 21:38 UTC, willian-soaresferreira commented on view/adminhtml/templates/marketplace/recipients/create.phtml
> +                                        <span><?php echo __('Use a existing Pagar.me recipient') ?></span>
~~Use a existing~~ -> Use **an** existing

2021-08-20 21:58 UTC, yanpantoja commented on view/adminhtml/templates/marketplace/recipients/create.phtml
> +                                        <input type="text" class="recipients_search" name="form[pagarme_id]" id="">
alterado para .recipient-form-inputs

2021-08-20 21:58 UTC, yanpantoja commented on Model/Api/Recipient.php
> +                'code' => 404,
corrigido!

2021-08-23 16:14 UTC, willian-soaresferreira approved these changes

2021-08-23 16:29 UTC, merged