Webkul integration
pagarme/magento2 pull request #55
Opened 2021-09-09 18:42 UTC by yanpantoja

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-251
| **What?**         | Integration with Webkul module
| **Why?**          | To allow payment with split
| **How?**          | Creating a WebkulHelp class

2021-09-09 20:12 UTC, netorodrigues requested changes

2021-09-09 20:12 UTC, netorodrigues commented on Helper/Marketplace/WebkulHelper.php
> +        if(!$sellerId && empty($splitData['sellers'])) {
Se a gente adicionou esse if só pra ver se pegamos dados de sellers ou não, podemos validar só a parte do `empty($splitData['sellers'])`

2021-09-09 20:12 UTC, netorodrigues commented on Helper/Marketplace/WebkulHelper.php
> +            $splitData = $this->sumSellersCommissionsIfArrayKeyExists(
Eu entendi como estão sendo usadas as funções `sumSellersCommissionsIfArrayKeyExists` e `setNewKeyIfArrayKeyNotExists`, mas acho que a gente consegue matar elas fazendo um fluxo tipo esse: 
```suggestion
            $sellerId = $sellerDetail['id'];
            $sellerDataForProduct = $this->getSellerData(
                $itemPrice,
                $sellerDetail
            );
            if (array_key_exists($sellerId, $splitData['sellers'])) {
               $splitData['sellers'][$sellerId]['sellerCommission'] += $sellerDataForProduct['sellers'][$sellerId]['sellerCommission'];
               continue;
            }
             $splitData['sellers'][$sellerId] = $sellerDataForProduct;
```

2021-09-09 22:54 UTC, yanpantoja commented on Helper/Marketplace/WebkulHelper.php
> +        if(!$sellerId && empty($splitData['sellers'])) {
corrigido!

2021-09-09 22:55 UTC, yanpantoja commented on Helper/Marketplace/WebkulHelper.php
> +            $splitData = $this->sumSellersCommissionsIfArrayKeyExists(
corrigido!

2021-09-10 21:48 UTC, netorodrigues approved these changes

2021-09-14 05:32 UTC, danielmadu approved these changes

2021-09-14 13:27 UTC, merged